### ISSUE TITLE
Lack of official plugin for cert-manager in IBM Cloud

### ISSUE THREAD

**Issue by jowko** [IBM/cert-manager-webhook-ibmcis#1]
Will this be implemented someday?
For now, there are some unofficial plugins only which are not actively maintained and which are not fully stable:
https://github.com/jb-dk/cert-manager-webhook-ibmcis
https://github.com/zachomedia/cert-manager-webhook-ibm-cis

**Comment by hughhuangzh** [comment]
@jowko the issue can be closed now?
