### ISSUE TITLE
Support for certificate manager 1.8.0 and above

### ISSUE THREAD

**Issue by roneymathew** [IBM/cert-manager-webhook-ibmcis#9]
on certificate manager 1.11.0  are getting the following error. API key is working with certificate manager 1.7.1
`E0615 06:02:58.910840       1 sync.go:282] cert-manager/challenges/finalizer "msg"="error cleaning up challenge" "error"="Request failed with status code: 400, BXNIM0415E: Transaction-Id:[YnB3N2g-2f1f059a6f4742d8a06965a7dd88ecb4] Provided API key could not be found" "dnsName"="" "resource_kind"="Challenge" "resource_name"="r" "resource_namespace"="" "resource_version"="v1" "type"="DNS-01"
`
And It's getting into a loop. which will not delete Challenge

**Comment by hughhuangzh** [comment]
Verified with 1.11.0, No issue, Please check your local configuration.
